### ISSUE TITLE
Support Vietnamese

### ISSUE THREAD

**Issue by davelab6** [jpt/barlow#15]
| Language (code) | Coverage | %Coverage | Missing Characters |
| ---- | ---- | ---- | ---- |
| Vietnamese (vi) | 104/157 | 66 | \u2010 (‐), \u0129 (ĩ), \u2032 (′), \u2033 (″), \u0169 (ũ), \u01a0 (Ơ), \u01a1 (ơ), \u1ea1 (ạ), \u1ea3 (ả), \u1ea5 (ấ), \u1ea7 (ầ), \u1ea9 (ẩ), \u1eab (ẫ), \u1ead (ậ), \u1eaf (ắ), \u01af (Ư), \u01b0 (ư), \u1eb1 (ằ), \u1eb3 (ẳ), \u1eb5 (ẵ), \u1eb7 (ặ), \u1eb9 (ẹ), \u1ebb (ẻ), \u1ebd (ẽ), \u1ebf (ế), \u1ec1 (ề), \u1ec3 (ể), \u1ec5 (ễ), \u1ec7 (ệ), \u1ec9 (ỉ), \u1ecb (ị), \u1ecd (ọ), \u1ecf (ỏ), \u1ed1 (ố), \u1ed3 (ồ), \u1ed5 (ổ), \u1ed7 (ỗ), \u1ed9 (ộ), \u1edb (ớ), \u1edd (ờ), \u1edf (ở), \u1ee1 (ỡ), \u1ee3 (ợ), \u1ee5 (ụ), \u1ee7 (ủ), \u1ee9 (ứ), \u1eeb (ừ), \u1eed (ử), \u1eef (ữ), \u1ef1 (ự), \u1ef5 (ỵ), \u1ef7 (ỷ), \u1ef9 (ỹ) |

**Comment by jpt** [comment]
Hey @crystaltype - @davelab6 recommended I get in touch in case you're available to help with bringing Vietnamese to Barlow, which I'm about to start on - let me know! I like your fork of Montserrat! :)

**Comment by jpt** [comment]
@crystaltype I have made some modifications based on your advice and will push them up shortly -- I think this particular pair is looking better now

<img width="313" alt="screen shot 2017-12-20 at 8 42 24 pm" src="https://user-images.githubusercontent.com/5319916/34240910-79e05b00-e5c6-11e7-8346-6a9701737237.png">

And a question RE: Acircumflextilde, I wonder if that's the kind of thing that needs a shortened version of the /A for, in order to not break winascent?

**Comment by jpt** [comment]
For a shortened A, this is what I'm referring to as a possibility

<img width="604" alt="screen shot 2017-12-20 at 8 58 05 pm" src="https://user-images.githubusercontent.com/5319916/34241188-9431b97a-e5c8-11e7-84c8-1a2e2b6a2f1f.png">

**Comment by jpt** [comment]
Although I think it's just a ring character that is ever drawn like that? So maybe not :) I think I will just change winAscent and see how it looks

**Comment by jpt** [comment]
CC @davelab6 @m4rc1e - would GF accept a PR with a different winAscent?

@crystaltype's original, winAscent is 1115

<img width="583" alt="screen shot 2017-12-26 at 3 36 44 am" src="https://user-images.githubusercontent.com/5319916/34355929-0cfea5ec-e9ee-11e7-9745-a0c15224f5b5.png">

Squished to use current winAscent, 981:

<img width="621" alt="screen shot 2017-12-26 at 3 36 12 am" src="https://user-images.githubusercontent.com/5319916/34355930-0d1425e8-e9ee-11e7-9bd2-713cd9f88cbf.png">

**Comment by jpt** [comment]
&num; 2 on this one is also an option using 981

![image](https://user-images.githubusercontent.com/5319916/34356058-2f22990c-e9ef-11e7-839b-fdcd97b94e1e.png)

**Comment by crystaltype** [comment]
I think squishing accents should never be an option to consider. I'll write more about this later. But it won't look good at all >< If we really can't accept a tall winaccent then at the moment the best choice is #2.

**Comment by jpt** [comment]
Ok, then there will be no squished accents. I didn't like them so I'm glad I can rule them out :)

It's too bad there isn't some clever way to do language-specific metrics in OpenType. If the double-stacked diacritics on /A/E do end up needing to be scaled down, maybe I can also write a build script to generate a set of Vietnamese-specific files with full size and different winAscent in case anyone wants it. 

changing winAscent makes most sense to me even if it messes up existing layouts because it kinda makes sense to do now while there aren't a ton of users yet. if this were a couple years in the future it'd be tougher.

**Comment by davelab6** [comment]
Any change that is an improvement is fine.



On Dec 26, 2017 8:22 PM, "Jeremy Tribby" <notifications@github.com> wrote:

Ok, then there will be no squished accents. I didn't like them so I'm glad
I can rule them out :)

It's too bad there isn't some clever way to do language-specific metrics in
OpenType. If the double-stacked diacritics on /A/E do end up needing to be
scaled down, maybe I can also write a build script to generate a set of
Vietnamese-specific files with full size and different winAscent in case
anyone wants it.

changing winAscent makes most sense to me even if it messes up existing
layouts because it kinda makes sense to do now while there aren't a ton of
users yet. if this were a couple years in the future it'd be tougher.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jpt/barlow/issues/15#issuecomment-354033377>, or mute
the thread

**Comment by crystaltype** [comment]
@jpt Yes, I think that's the best course of actions right now.

I'm gonna write up a post in your post at typedrawers but I'm gathering more materials to that post, hopefully will give you more insights to the problem.

**Comment by jpt** [comment]
@crystaltype I changed the winAscent to 1112 and I think it's fine / didn't impact line spacing too much. Your original, large, legible diacritics look great :)

I was mostly worried about this because in a GF pull request from a while ago Marc mentioned wanting to lock in the metrics. So Vietnamese is basically done, I think -- can't remember if I pushed the latest (I didn't add binaries yet because I need to run them through FontBakery for testing, which I've been having issues with) but I'll double check in a few hours and let you know so you can give it a final thumbs-up!

On that typedrawers thread I think I agreed most with John Hudson who thinks there should be language specific metrics in OT spec. In retrospect it was silly of me to think visually squishing diacritics is ever an acceptable solution -- it seems disrespectful to the language itself.

**Comment by jpt** [comment]
Hi @crystaltype sorry that took longer than expected -- v1.3 is now up (release with binaries from this and #14 generated). https://github.com/jpt/barlow/archive/v1.300.zip
Let me know what you think of the Vietnamese support!

**Comment by jpt** [comment]
@crystaltype Just fixed all winAscent/winDescent errors I was getting from FontBakery, so I'm going to close this issue for now, but please let me know if you notice I've accidentally messed anything up, and I will re-open the issue! Only changes I made to your contributions should be slight. I also made the breve a bit wider and more distinct from caron which helps at small sizes.
