### ISSUE TITLE
Alternative lower case g

### ISSUE THREAD

**Issue by vilav** [jpt/barlow#24]
Typography Noob here. But Barlow is perfect. While I reckon the g does lend a personality to the typeface, had to recently switch it out on a project because the client found the g to be an of all amongst all the other letter forms.

Is there a way to tweak the font and add in an extended tail to the g such that it is elongated without looking out of place?

**Comment by jpt** [comment]
Hi @vilav -- thanks for opening the issue. The /g is modeled a bit after [Highway Gothic](https://en.wikipedia.org/wiki/Highway_Gothic) and I don't plan to change it, but it's possible I could add a stylistic alternate to the glyph set. Right now the main focus of the Barlow project is on adding additional language support, so unfortunately it's not likely to happen soon.

**Comment by jpt** [comment]
Glyphs is the best way to edit it because it's what the font was created in. The Barlow.glyphs file has a number of Glyphs-specific export parameters to do things like rounding, creating the faux obliques, and to take care of some necessary font metadata; it also makes liberal use of a Glyphs feature called [brace layers](https://glyphsapp.com/tutorials/additional-masters-for-individual-glyphs-the-brace-trick) to avoid the need for a Semi Condensed master. It's certainly possible to edit Barlow outside of Glyphs: the newest version of FontLab can import Glyphs files (although I don't know if that includes the aforementioned Glyphs-specific features); you could also export to UFO from within Glyphs (although the masters wont be compatible) for use in another editor like RoboFont or TruFont; and you could even open the TTF/OTF binaries in a font editor and then re-export. That last suggestion would require modifying all 54 styles, but you're probably not using all of them, so it could be the fastest way to do it. In a nutshell, if you want to _properly_ generate TTF/OTF binaries the way it's happening now, you'll need Glyphs, but don't let that stop you from hacking on the font in other ways :) 

Regarding the design of the /g, there is indeed a relationship between the /s and /g in many typefaces, although you'll find the /s in Barlow terminates at 90º angle, so you'll probably have to chop off the tail before it turns upward like that. The /e especially at the Black weight might provide some inspiration. Good luck!
