### ISSUE TITLE
Ø in bold has low readability

### ISSUE THREAD

**Issue by Maggern** [jpt/barlow#41]
The ø/Ø-character does not have a full line through it in the bolder versions. This creates low readability, as it is hard to see that it is a Ø and not a O. It's not a "Ø" unless there is a whole line through the "O"! 

**Suggested solution:** Sacrificy some of the boldness of the line in order to have a full line.

**Comment by Maggern** [comment]
I suggest undoing issue #21

**Comment by jpt** [comment]
Thanks @Maggern ! I agree; I should change this and add the current ø as an alternate glyph. Will close issue when I've made the change. Barlow should get this along with some other improvements soon, hard to give an exact estimate on time, but there is an active effort right now, and this is in the queue :)

**Comment by mancas11** [comment]
Any news on this matter?

**Comment by jpt** [comment]
Hi @mancas11 @Maggern -- this is fixed in [version 1.422, which you can download here](https://github.com/jpt/barlow/archive/master.zip) (you'll find the files in the `fonts` folder). Will update with distributors soon. Thanks again for bringing this to my attention. And if there's still a legibility issue, feel free to ping me and I'll re-open.

**Comment by Maggern** [comment]
Great! Thank you so much for the fix and for this beautiful font!
