### ISSUE TITLE
problem displaying these letters "ffi" together

### ISSUE THREAD

**Issue by sofdesigne** [jpt/barlow#52]
Hi, i am using the font on my website via google fonts, and i noticed that there is a problem displaying these letters "ffi" together, letters are hidden, words like efficient, affirmative will show with spaces in the middle, i tried firefox but ! same issue, any ideas please ?!
![ScreenShot080](https://user-images.githubusercontent.com/50580979/57619621-3a8a9300-757e-11e9-907d-e9ff7b0d74e4.jpg)

**Comment by jpt** [comment]
Hi @sofdesigne can you let me know if this is fixed in the latest [version 1.422, which you can download here](https://github.com/jpt/barlow/archive/master.zip) (you'll find the files in the `fonts` folder). I'm going to go ahead and close the issue, but LMK if there's still a problem and I'll reopen it.

cc @davelab6 @m4rc1e RE: GF specimen. Ligatures probably need a little work (there's a Barlow 1.5 milestone coming soon), but 1.422 is iKerned 😄

**Comment by sofdesigne** [comment]
Thanks for your response, but i was talking about google fonts, the issue is not when i use the font with illustrator or whatever program, the issue is web based, check the google fonts website and you will understand

**Comment by Azgaar** [comment]
Hi @jpt,

Could you please upload a new version to Google Fonts? I can see some web-pages affected.

**Comment by fitojb** [comment]
@Azgaar It’s not up to him; he doesn’t work at Google.

**Comment by orionseye** [comment]
why do don't fix the issue with these dual ff letters?
it's everywhere.. and if your new releases fix the issue, why not contact Google as creator to mention the bug?
It's 2+ years now since issue has been mentioned
i first saw the bug at https://www.coupler.io and a couple of other sites
